export const formationsData = [
  {
    docId: '4-3-3',
    fields: [
      { name: 'order', type: 'number', value: 1 },
      { name: 'titleKey', type: 'string', value: 'f433_title' },
      { name: 'style', type: 'string', value: 'Offensive' },
      { name: 'difficulty', type: 'string', value: 'Medium' },
      { name: 'descriptionKey', type: 'string', value: 'f433_desc' },
      { name: 'summaryKey', type: 'string', value: 'f433_summary' },
      { name: 'idealForKey', type: 'string', value: 'f433_ideal' },
      { name: 'advantages', type: 'array', value: ['adv_num_attack', 'adv_high_press', 'adv_width', 'adv_triangles'] },
      { name: 'disadvantages', type: 'array', value: ['dis_counter', 'dis_physical', 'dis_mid_inferior'] },
      { name: 'famousTeams', type: 'array', value: ['team_barca_guardiola', 'team_liverpool', 'team_ajax_cruyff'] },
      { name: 'keyRoles', type: 'array', value: ['role_regista', 'role_winger', 'role_false_nine'] },
      { name: 'positions', type: 'json', value: JSON.stringify([
        { x: 50, y: 5, role: 'GK' },
        { x: 20, y: 20, role: 'LB' },
        { x: 40, y: 18, role: 'LCB' },
        { x: 60, y: 18, role: 'RCB' },
        { x: 80, y: 20, role: 'RB' },
        { x: 50, y: 35, role: 'DM' },
        { x: 35, y: 50, role: 'LCM' },
        { x: 65, y: 50, role: 'RCM' },
        { x: 25, y: 75, role: 'LW' },
        { x: 75, y: 75, role: 'RW' },
        { x: 50, y: 85, role: 'ST' },
      ]) },
    ],
  },
  {
    docId: '3-4-3',
    fields: [
      { name: 'order', type: 'number', value: 7 },
      { name: 'titleKey', type: 'string', value: 'f343_title' },
      { name: 'style', type: 'string', value: 'Offensive' },
      { name: 'difficulty', type: 'string', value: 'Hard' },
      { name: 'descriptionKey', type: 'string', value: 'f343_desc' },
      { name: 'summaryKey', type: 'string', value: 'f343_summary' },
      { name: 'idealForKey', type: 'string', value: 'f343_ideal' },
      { name: 'advantages', type: 'array', value: ['adv_attack_overload', 'adv_flexible_mid', 'adv_press_high', 'adv_width_control'] },
      { name: 'disadvantages', type: 'array', value: ['dis_def_iso', 'dis_wingback_demand', 'dis_transition_vuln', 'dis_complex'] },
      { name: 'famousTeams', type: 'array', value: ['team_chelsea_conte', 'team_atalanta_gasp', 'team_ajax_cruyff'] },
      { name: 'keyRoles', type: 'array', value: ['role_wing_back', 'role_playmaker', 'role_mobile_striker'] },
      { name: 'positions', type: 'json', value: JSON.stringify([
        { x: 50, y: 5, role: 'GK' },
        { x: 30, y: 15, role: 'LCB' },
        { x: 50, y: 15, role: 'CB' },
        { x: 70, y: 15, role: 'RCB' },
        { x: 15, y: 50, role: 'LWB' },
        { x: 40, y: 45, role: 'LCM' },
        { x: 60, y: 45, role: 'RCM' },
        { x: 85, y: 50, role: 'RWB' },
        { x: 25, y: 80, role: 'LF' },
        { x: 50, y: 85, role: 'ST' },
        { x: 75, y: 80, role: 'RF' },
      ]) },
    ],
  },
  {
    docId: '4-4-2',
    fields: [
      { name: 'order', type: 'number', value: 2 },
      { name: 'titleKey', type: 'string', value: 'f442_title' },
      { name: 'style', type: 'string', value: 'Balanced' },
      { name: 'difficulty', type: 'string', value: 'Low' },
      { name: 'descriptionKey', type: 'string', value: 'f442_desc' },
      { name: 'summaryKey', type: 'string', value: 'f442_summary' },
      { name: 'idealForKey', type: 'string', value: 'f442_ideal' },
      { name: 'advantages', type: 'array', value: ['adv_def_struct', 'adv_simple', 'adv_two_striker_options', 'adv_wide_coverage'] },
      { name: 'disadvantages', type: 'array', value: ['dis_mid_flat', 'dis_gaps_between_lines_442', 'dis_predictable_attack', 'dis_less_creativity'] },
      { name: 'famousTeams', type: 'array', value: ['team_milan_sacchi', 'team_leicester_ranieri', 'team_atletico_simeone'] },
      { name: 'keyRoles', type: 'array', value: ['role_hard_working_mid', 'role_classic_winger', 'role_strike_partnership', 'role_second_striker'] },
      { name: 'positions', type: 'json', value: JSON.stringify([
        { x: 50, y: 5, role: 'GK' },
        { x: 20, y: 25, role: 'LB' },
        { x: 40, y: 22, role: 'LCB' },
        { x: 60, y: 22, role: 'RCB' },
        { x: 80, y: 25, role: 'RB' },
        { x: 25, y: 50, role: 'LM' },
        { x: 45, y: 50, role: 'LCM' },
        { x: 55, y: 50, role: 'RCM' },
        { x: 75, y: 50, role: 'RM' },
        { x: 40, y: 80, role: 'LS' },
        { x: 60, y: 80, role: 'RS' },
      ]) },
    ],
  },
  {
    docId: '3-5-2',
    fields: [
      { name: 'order', type: 'number', value: 8 },
      { name: 'titleKey', type: 'string', value: 'f352_title' },
      { name: 'style', type: 'string', value: 'Balanced' },
      { name: 'difficulty', type: 'string', value: 'Hard' },
      { name: 'descriptionKey', type: 'string', value: 'f352_desc' },
      { name: 'summaryKey', type: 'string', value: 'f352_summary' },
      { name: 'idealForKey', type: 'string', value: 'f352_ideal' },
      { name: 'advantages', type: 'array', value: ['adv_mid_domination', 'adv_width_from_wingbacks', 'adv_two_strikers_presence', 'adv_flexible_mid_setup'] },
      { name: 'disadvantages', type: 'array', value: ['dis_wingbacks_demanding', 'dis_vulnerable_wide_counters', 'dis_defenders_exposed', 'dis_complex_coordination'] },
      { name: 'famousTeams', type: 'array', value: ['team_juve_conte', 'team_inter_conte', 'team_germany_1990'] },
      { name: 'keyRoles', type: 'array', value: ['role_wing_back', 'role_regista', 'role_box_to_box', 'role_second_striker'] },
      { name: 'positions', type: 'json', value: JSON.stringify([
        { x: 50, y: 5, role: 'GK' },
        { x: 30, y: 15, role: 'LCB' },
        { x: 50, y: 15, role: 'CB' },
        { x: 70, y: 15, role: 'RCB' },
        { x: 15, y: 50, role: 'LWB' },
        { x: 50, y: 35, role: 'DM' },
        { x: 35, y: 55, role: 'LCM' },
        { x: 65, y: 55, role: 'RCM' },
        { x: 85, y: 50, role: 'RWB' },
        { x: 40, y: 80, role: 'LS' },
        { x: 60, y: 80, role: 'RS' },
      ]) },
    ],
  },
  {
    docId: '4-2-3-1',
    fields: [
      { name: 'order', type: 'number', value: 3 },
      { name: 'titleKey', type: 'string', value: 'f4231_title' },
      { name: 'style', type: 'string', value: 'Balanced' },
      { name: 'difficulty', type: 'string', value: 'Medium' },
      { name: 'descriptionKey', type: 'string', value: 'f4231_desc' },
      { name: 'summaryKey', type: 'string', value: 'f4231_summary' },
      { name: 'idealForKey', type: 'string', value: 'f4231_ideal' },
      { name: 'advantages', type: 'array', value: ['adv_def_solidity_double_pivot', 'adv_attacking_flexibility_4231', 'adv_space_for_am', 'adv_good_for_possession'] },
      { name: 'disadvantages', type: 'array', value: ['dis_lone_striker_isolation_4231', 'dis_gap_between_dm_am', 'dis_demands_on_fullbacks', 'dis_can_be_defensive'] },
      { name: 'famousTeams', type: 'array', value: ['team_real_mourinho', 'team_bayern_heynckes', 'team_france_2018'] },
      { name: 'keyRoles', type: 'array', value: ['role_double_pivot', 'role_attacking_midfielder_10', 'role_inverted_winger', 'role_lone_striker_hold_up'] },
      { name: 'positions', type: 'json', value: JSON.stringify([
        { x: 50, y: 5, role: 'GK' },
        { x: 20, y: 25, role: 'LB' },
        { x: 40, y: 22, role: 'LCB' },
        { x: 60, y: 22, role: 'RCB' },
        { x: 80, y: 25, role: 'RB' },
        { x: 40, y: 40, role: 'LDM' },
        { x: 60, y: 40, role: 'RDM' },
        { x: 25, y: 65, role: 'LAM' },
        { x: 50, y: 65, role: 'CAM' },
        { x: 75, y: 65, role: 'RAM' },
        { x: 50, y: 85, role: 'ST' },
      ]) },
    ],
  },
];
